### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by edolyne** [picdorsey/craft-sidebarenhancer#11]
**Plugin Version:** 1.0.8
**Craft Version:** 2.6.2983

After updating to the latest version(1.0.8), I'm receiving this error on the front end of the website when you aren't logged in, it also prevents users from accessing the control panel login.

```
Trying to get property of non-object (/storage/av03567/www/craft/plugins/sidebarenhancer/services/SidebarEnhancerService.php:32)
```

**Comment by nicholasodonnell** [comment]
Whoops sorry about that! The latest update introduced a new feature to disable the sidebar for specific admins. I reference the user object to achieve this, and it looks like Craft sets it to null when no one is logged-in (duh).
