### ISSUE TITLE
Huge performance problem

### ISSUE THREAD

**Issue by timkelty** [picdorsey/craft-sidebarenhancer#8]
The latest update (1.0.7) introduced a huge performance problem - you're looping through EVERY user to get only those who are admins.

My site has 50k+ users...so naturally it brought things to a screeching halt.

Additionally, I think it's a bad idea to do any sort of query in `defineSettings`, as that is going to get called on every request. You should instead either add those defaults when installing, or as part of the `getSettings` call.

PR coming.

**Comment by timkelty** [comment]
🤗

**Comment by nicholasodonnell** [comment]
Oh wow, very nice catch! Apologies for the performance issues you're absolutely right. I've accepted your pull request; a point update is coming. Thanks for all your help.

**Comment by timkelty** [comment]
Thanks for the quick merge.
